ufe: Peptide::VersionFormat< VersionTrait > Class Template Reference
ufe: Peptide::VersionFormat< VersionTrait > Class Template Reference
Peptide::VersionFormat< VersionTrait > Class Template Reference
Utility class for formatting version information.
#include <VerFormat.h>
Static Public Member Functions
static std::string getVersionID ()
Returns a short version identifier for the given version trait.
static std::string getVersionInfo ()
Returns detailed information for the given version trait.
Private Member Functions
VersionFormat ()=delete
Prohibited and not implemented.
Detailed Description
template<class VersionTrait>
class Peptide::VersionFormat< VersionTrait >
Utility class for formatting version information.
The VersionTrait is typically generated using CMake configuration files. It contains all of the version information of given component (library, executable, etc.). This class contains functions to format this version information to a human readable form.
The VersionTrait must provide the following static member functions:
static int         getMajorVersion();
static int         getMinorVersion();
static int         getPatchLevel();
static char const* getGitCommit();
static char const* getGitBranch();
static int         getBuildNumber();
static char const* getBuildDate();
static char const* getProductName();
Template Parameters
VersionTrait CMake generated version trait.
Definition at line 58 of file VerFormat.h.
Constructor & Destructor Documentation
VersionFormat()
template<class VersionTrait > Peptide::VersionFormat< VersionTrait >::VersionFormat () private delete
Prohibited and not implemented.
Don't allow construction since we only have static member functions.
Member Function Documentation
getVersionID()
template<class VersionTrait > static std::string Peptide::VersionFormat< VersionTrait >::getVersionID () inline static
Returns a short version identifier for the given version trait.
Returns a short version identifier such as for example "3.0.2".
Definition at line 65 of file VerFormat.h.
Referenced by Peptide::VersionFormat< VersionTrait >::getVersionInfo().
getVersionInfo()
template<class VersionTrait > static std::string Peptide::VersionFormat< VersionTrait >::getVersionInfo () inline static
Returns detailed information for the given version trait.
Returns detailed information about the version of the binary such as for example:
"MyProduct version 4.0.0 (Mon 09/28/2015, 201509282010, build 34567, commit b5283ef, branch origin/master)"
Note that only the short git hash is included.
Definition at line 82 of file VerFormat.h.
References Peptide::VersionFormat< VersionTrait >::getVersionID(), and Ufe::PathString::string().
The documentation for this class was generated from the following file:
include/peptide/versioning/VerFormat.h
Please send us your comment about this page