ufe: Ufe::BaseUndoableCommand Class Reference
ufe: Ufe::BaseUndoableCommand Class Reference
Ufe::BaseUndoableCommand Class Reference
Base class for undoable set operation commands.
#include <baseUndoableCommands.h>
Public Member Functions
BaseUndoableCommand (const Path &path)
virtual ~BaseUndoableCommand ()
void setPath (const Path &path)
Set the path of the object onto which the command is applied.
const Path & path () const
Ufe::SceneItem::Ptr sceneItem () const
Public Member Functions inherited from Ufe::UndoableCommand
virtual ~UndoableCommand ()
Destructor.
virtual void execute ()
virtual void undo ()=0
virtual void redo ()=0
Private Attributes
Path fPath
Additional Inherited Members
Public Types inherited from Ufe::UndoableCommand
typedef std::shared_ptr< UndoableCommand > Ptr
Protected Member Functions inherited from Ufe::UndoableCommand
UndoableCommand ()
Constructor.
UndoableCommand (const UndoableCommand &)=delete
Deleting copy constructor.
Detailed Description
Base class for undoable set operation commands.
Definition at line 32 of file baseUndoableCommands.h.
Constructor & Destructor Documentation
BaseUndoableCommand()
Ufe::BaseUndoableCommand::BaseUndoableCommand (const Path & path)
~BaseUndoableCommand()
virtual Ufe::BaseUndoableCommand::~BaseUndoableCommand () virtual
Member Function Documentation
path()
const Path& Ufe::BaseUndoableCommand::path () const inline
Returns
the path of the object onto which the command is applied.
Definition at line 42 of file baseUndoableCommands.h.
sceneItem()
Ufe::SceneItem::Ptr Ufe::BaseUndoableCommand::sceneItem () const inline
Returns
the object's SceneItem
Definition at line 45 of file baseUndoableCommands.h.
References Ufe::Hierarchy::createItem(), and Ufe::PathString::path().
setPath()
void Ufe::BaseUndoableCommand::setPath (const Path & path) inline
Set the path of the object onto which the command is applied.
Definition at line 39 of file baseUndoableCommands.h.
References Ufe::PathString::path().
Member Data Documentation
fPath
Path Ufe::BaseUndoableCommand::fPath private
Definition at line 48 of file baseUndoableCommands.h.
The documentation for this class was generated from the following file:
include/ufe/baseUndoableCommands.h
Please send us your comment about this page