ufe: Ufe::TypedVector3< T > Struct Template Reference
ufe: Ufe::TypedVector3< T > Struct Template Reference
Ufe::TypedVector3< T > Struct Template Reference
Typed vector template for creating a specialized vector.
#include <types.h>
Public Member Functions
TypedVector3 ()
TypedVector3 (T x, T y, T z)
T x () const
T y () const
T z () const
void set (T x, T y, T z)
bool operator== (const TypedVector3< T > &rhs) const
bool operator!= (const TypedVector3< T > &rhs) const
Public Attributes
std::array< T, 3 > vector
Detailed Description
template<typename T>
struct Ufe::TypedVector3< T >
Typed vector template for creating a specialized vector.
Definition at line 24 of file types.h.
Constructor & Destructor Documentation
TypedVector3() [1/2]
template<typename T> Ufe::TypedVector3< T >::TypedVector3 () inline
Definition at line 26 of file types.h.
TypedVector3() [2/2]
template<typename T> Ufe::TypedVector3< T >::TypedVector3 (T x, T y, T z) inline
Definition at line 31 of file types.h.
Member Function Documentation
operator!=()
template<typename T> bool Ufe::TypedVector3< T >::operator!= (const TypedVector3< T > & rhs) const inline
Definition at line 46 of file types.h.
operator==()
template<typename T> bool Ufe::TypedVector3< T >::operator== (const TypedVector3< T > & rhs) const inline
Definition at line 41 of file types.h.
set()
template<typename T> void Ufe::TypedVector3< T >::set (T x, T y, T z) inline
Definition at line 39 of file types.h.
x()
template<typename T> T Ufe::TypedVector3< T >::x () const inline
Definition at line 36 of file types.h.
Referenced by Ufe::BBox3d::empty(), and Ufe::operator<<().
y()
template<typename T> T Ufe::TypedVector3< T >::y () const inline
Definition at line 37 of file types.h.
Referenced by Ufe::BBox3d::empty(), and Ufe::operator<<().
z()
template<typename T> T Ufe::TypedVector3< T >::z () const inline
Definition at line 38 of file types.h.
Referenced by Ufe::BBox3d::empty(), and Ufe::operator<<().
Member Data Documentation
vector
template<typename T> std::array<T, 3> Ufe::TypedVector3< T >::vector
Definition at line 51 of file types.h.
Referenced by Ufe::BBox3d::BBox3d(), Ufe::TypedVector3< double >::operator!=(), and Ufe::TypedVector3< double >::operator==().
The documentation for this struct was generated from the following file:
include/ufe/types.h
Please send us your comment about this page