ufe: Ufe::BBox3d Struct Reference
ufe: Ufe::BBox3d Struct Reference
Ufe::BBox3d Struct Reference
3D bounding box class.
#include <types.h>
Public Member Functions
BBox3d ()
Create an empty bounding box.
BBox3d (const Vector3d &aMin, const Vector3d &aMax)
bool empty () const
Public Attributes
Vector3d min
Vector3d max
Detailed Description
3D bounding box class.
Axis-aligned 3D bounding box class. Considered empty if the minimum in any dimension is greater than the maximum.
Definition at line 97 of file types.h.
Constructor & Destructor Documentation
BBox3d() [1/2]
Ufe::BBox3d::BBox3d () inline
Create an empty bounding box.
Definition at line 103 of file types.h.
References Ufe::TypedVector3< T >::vector.
BBox3d() [2/2]
Ufe::BBox3d::BBox3d (const Vector3d & aMin, const Vector3d & aMax) inline
Definition at line 108 of file types.h.
Member Function Documentation
empty()
bool Ufe::BBox3d::empty () const inline
Definition at line 110 of file types.h.
References Ufe::TypedVector3< T >::x(), Ufe::TypedVector3< T >::y(), and Ufe::TypedVector3< T >::z().
Member Data Documentation
max
Vector3d Ufe::BBox3d::max
Definition at line 100 of file types.h.
Referenced by Ufe::operator<<().
min
Vector3d Ufe::BBox3d::min
Definition at line 99 of file types.h.
Referenced by Ufe::operator<<().
The documentation for this struct was generated from the following file:
include/ufe/types.h
Please send us your comment about this page