# Basic
title: 许铮
subtitle: 学习 / 生活 / 工作 / 娱乐
#welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">下载这个主题</a>
description: 不为无益之事,何以遣有涯之生.
creator: <a href="https://a690089735.github.io/">@许铮</a>

# 基本链接 下面两个是资源床
#url: "https://a690089735.github.io/"
#img: "https://a690089735.imfast.io/images/"
#pic: "https://a690089735.imfast.io/picture/"
url: "https://a690089735.gitee.io/"
img: "/assets-images/"
pic: "/assets-picture/"
video: "/assets-video/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty. gray
cover_color: 

# The blog button should not be removed.
blog_button:
    title: 首页
    description: 博客主页

# Navigation buttons in the front page.
nav:
    - {title: 归档, description: 按时间查看全部博文, url: '/posts'}
    - {title: 标签, description: 按标签检索文章, url: '/tags'}
    - {title: 作品, description: 阅览我的职业作品, url: '/works'}

# Pagination
plugins: [jekyll-paginate]
paginate: 32
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 
    github: 
    twitter: 
    #gplus: 107108267983477358170
    mail: 690089735@qq.com

# Google Analytics
ga:
    # id: 174168556-1
    # host: your_host
