$Lingzhuxie_LimbA_SIK_R_001[3].VHTarget = $Lingzhuxie_LimbA_TN_R_002
$Lingzhuxie_LimbB_SIK_R_001[3].VHTarget = $Lingzhuxie_LimbA_TN_R_005
$Lingzhuxie_LimbC_SIK_R_001[3].VHTarget = $Lingzhuxie_LimbC_TN_R_002
$Lingzhuxie_LimbD_SIK_R_001[3].VHTarget = $Lingzhuxie_LimbD_Bn_R_002_R_002

$Lingzhuxie_LimbA_SIK_L_001[3].VHTarget = $Lingzhuxie_LimbA_TN_L_002
$Lingzhuxie_LimbB_SIK_L_001[3].VHTarget = $Lingzhuxie_LimbA_TN_L_005
$Lingzhuxie_LimbC_SIK_L_001[3].VHTarget = $Lingzhuxie_LimbC_TN_L_002
$Lingzhuxie_LimbD_SIK_L_001[3].VHTarget = $Lingzhuxie_LimbD_Bn_L_002_L_002