createPreview outputAVI:true percentSize:100 \
start:(animationRange.start.frame as integer) end:(animationRange.end.frame as integer) skip:1 fps:frameRate \
dspGeometry:true dspShapes:false dspLights:false \
dspCameras:false dspHelpers:false dspParticles:false dspBones:false \
dspGrid:false dspSafeFrame:false dspFrameNums:true dspBkg:true \
rndLevel:#flat \
filename:@"C:\Users\LiSa\Desktop\preview.avi"
-- (<#smoothhighlights | #smooth | #facethighlights | #facet | #flat | #hiddenline | #litwireframe | #wireframe | #box>) 

-- frameRate 